### ISSUE TITLE
flows node red para mediçao de energia

### ISSUE THREAD

**Issue by polyphia** [remontti/MyHa#2]
Parabéns pelo interface de lovelace e todo o setup, é o melhor que já vi de muitos até agora e estou a basear todo o meu interface nele, impossível fazer melhor ! :) 

Estou apenas com algumas dificuldades na parte da integraçao de energia, seria possível partilhar as flows de node red com estes sensores ? (consumos diarios, ultimo dia, semana, etc)

Obrigado pela inspiraçao!

**Comment by remontti** [comment]
Bom dia, obrigado. Não uso nodred. :)

Em qui, 12 de dez de 2019 00:27, TriptonPt <notifications@github.com>
escreveu:

**Comment by polyphia** [comment]
Ah, de onde vem aqueles json entao ? value_json.ENERGY.Power , etc ?

**Comment by remontti** [comment]
> Ah, de onde vem aqueles json entao ? value_json.ENERGY.Power , etc ?

Acessa o console do seu sonoff e olhe os logs, aproveitando vai nas configurações de log e baixe o tempo para 10s para ter um intervalo de atualização mais rápido
